name: Make a Prerelease from a Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[A-z]'
env:
  APP_NAME: Clamfall
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set Environment
        run: sudo xcrun xcode-select -s /Applications/Xcode_16.2.app
      - name: Update Build Number
        env:
          TAG_NAME: ${{ github.ref }}
          RUN_ID: ${{ github.run_id }}
        run: |
          export CLEAN_TAG=$(echo $TAG_NAME | sed -e 's/refs\/tags\///')
          bundle install
          bundle exec fastlane bump market_version:$CLEAN_TAG current_project_version:1.$RUN_ID
          echo "### Version for $APP_NAME" >> $GITHUB_STEP_SUMMARY
          echo "$CLEAN_TAG" >> $GITHUB_STEP_SUMMARY
      - name: Build
        run: bundle exec fastlane build
      - name: Create ZIPs
        run: |
          ditto -c -k --sequesterRsrc --keepParent ./Archive.xcarchive/Products/Applications/$APP_NAME.app ./$APP_NAME.zip
      - name: Get the file hash sha256 of the ZIP
        run: |
          echo "### Hash for $APP_NAME" >> $GITHUB_STEP_SUMMARY
          shasum -a 256 $APP_NAME.zip >> $GITHUB_STEP_SUMMARY
      - name: Create a new Release and Upload App
        uses: softprops/action-gh-release@v2
        with:
          files: eikana.zip
          body: |
            Update description
            
            ## Features
            
            ## Fixes
            
            ## Minimum macOS Version
          draft: true
