name: tagpr
on:
  push:
    branches: ["main"]
env:
  APP_NAME: Clamfall
jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tag: ${{ steps.tagpr.outputs.tag }}
    steps:
    - uses: actions/checkout@v4
    - uses: Songmu/tagpr@v1
      id: tagpr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: tagpr
    runs-on: macos-latest
    timeout-minutes: 10
    outputs:
      app_name: $APP_NAME
    if: needs.tagpr.outputs.tag != ''
    steps:
    - uses: actions/checkout@v4
    - name: Set Environment
      run: sudo xcrun xcode-select -s /Applications/Xcode_16.2.app
    - name: Update Build Number
      env:
        TAG_NAME: ${{ needs.tagpr.outputs.tag }}
        RUN_ID: ${{ github.run_id }}
      run: |
          export CLEAN_TAG=$(echo $TAG_NAME | sed -e 's/refs\/tags\///')
          bundle install
          bundle exec fastlane bump market_version:$CLEAN_TAG current_project_version:1.$RUN_ID
          echo "### Version for $APP_NAME" >> $GITHUB_STEP_SUMMARY
          echo "$CLEAN_TAG" >> $GITHUB_STEP_SUMMARY
    - name: Build
      run: bundle exec fastlane build
    - name: Create ZIPs
      run: |
        ditto -c -k --sequesterRsrc --keepParent ./Archive.xcarchive/Products/Applications/$APP_NAME.app ./$APP_NAME.zip
    - name: Get the file hash sha256 of the ZIP
      run: |
        echo "### Hash for $APP_NAME" >> $GITHUB_STEP_SUMMARY
        shasum -a 256 $APP_NAME.zip >> $GITHUB_STEP_SUMMARY
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create a new Release and Upload App
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ needs.build.outputs.app_name }}.zip
          body: |
            Update description
            
            ## Features
            
            ## Fixes
            
            ## Minimum macOS Version
          draft: true
